#!/usr/bin/python

def accomodation(elemets, by):
    if (by > 1):
        return elements * accomodation(elements - 1, by - 1)
    else:
        return 1

print("Input nuber of elements: ");
elements = int(input())
print("Input by numbers to  accomodation: ");
by = int(input())
print('Accomodation {} elements by {} items has {} accomodations'.format(elements, by, accomodation(elements, by)))

# vim set ft=python;
    
