#!/usr/bin/python

def accomodation(list, by, result = 1):
    result *= list
    if (by > 0):
        return accomodation(list - 1, by - 1, result)
    else:
       return result


listLenght = int(input("Input list length: "))
by = int(input("Input elements length: "))
print('Accomodation {} length  list by {} is: {}'.format(listLenght, by, accomodation(listLenght, by)))

# vim set ft=python

