#!/usr/bin/python

def factorial(number):
    if (number > 1):
        return number * factorial(number - 1)
    elif (number >= 0):
        return 1
    else:
        return "NaN"


num = int(input("Input a number: "))
print('Factorial of {} is: {}'.format(num, factorial(num)))

#vim set ft=python

